ModLoader.SetupFileHook( "lua/Badges_Shared.lua", "lua/UWEExtension/Build_323/Badges_Shared.lua", "replace" )
ModLoader.SetupFileHook( "lua/NS2Gamerules.lua", "lua/UWEExtension/Build_323/NS2Gamerules.lua", "replace" )
ModLoader.SetupFileHook( "lua/Weapons/Alien/Spit.lua", "lua/UWEExtension/Build_323/Spit.lua", "replace" )
ModLoader.SetupFileHook( "lua/Weapons/Alien/LerkBite.lua", "lua/UWEExtension/Build_323/LerkBite.lua", "replace" )
ModLoader.SetupFileHook( "lua/DamageTypes.lua", "lua/UWEExtension/Build_323/DamageTypes.lua", "replace" )
ModLoader.SetupFileHook( "lua/AlienCommander.lua", "lua/UWEExtension/Build_323/AlienCommander.lua", "replace" )